server:
  port: 8081

mybatis:
  config-location: classpath:mybatis/config.xml
  mapper-locations: classpath*:mybatis/mapper/*.xml #扫描tcc-support包的xml
#dataSource 配置
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: >
        jdbc:mysql://127.0.0.1:3306/X_SPONSOR
        ?useUnicode=true
        &serverTimezone=GMT%2B8
        &characterEncoding=utf-8
        &allowMutiQueries=true
    username: root
    password: root